### ISSUE TITLE
使用请看WIKI文档

### ISSUE THREAD

**Issue by fail572872916** [D10NGYANG/DLCommonUtil#1]
并没有找到wiki文档，哈哈

**Comment by D10NGYANG** [comment]
https://github.com/D10NGYANG/DLCommonUtil/wiki

<img width="939" alt="image" src="https://github.com/D10NGYANG/DLCommonUtil/assets/33045730/241844ab-7ad1-47e0-86b2-b3b5c3e3423f">

**Comment by fail572872916** [comment]
> https://github.com/D10NGYANG/DLCommonUtil/wiki
> 
> <img alt="image" width="939" src="https://private-user-images.githubusercontent.com/33045730/331954194-241844ab-7ad1-47e0-86b2-b3b5c3e3423f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3MzgsIm5iZiI6MTcxNjE4MzQzOCwicGF0aCI6Ii8zMzA0NTczMC8zMzE5NTQxOTQtMjQxODQ0YWItN2FkMS00N2UwLTg2YjItYjNiNWMzZTM0MjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA1MzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZTc4MDFkMTgwZTQ5M2RmNjJiNjMyZWRmMzEwMThlMzBhOWNmYWJkYjk3MGYzMzhhNzEyMGQ5MGRkNDQ0MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jrWNM53-H50G80x6MqpXbuIWigy0E2LdVGA78NH7SlA">

感谢大佬的回答
